slackhq/csp-html-webpack-plugin

README.md
plugin.js

Currently, if you pull in the manifest asset, it's children are defined as all of the other assets in the build.
This causes the plugin to hash *all* assets in the build, rather than only the smaller subset that the developer has defined using the `cspAssetRegex` option.
This change ignores the children of the manifest asset when recursively iterating through the assets to hash

Ignoring the children of manifest assets when using cspAssetRegex

---

.github/PULL_REQUEST_TEMPLATE.md
plugin.js

Making sure that apostropes are preserved as cheerio was escaping them

Making sure that apostropes are preserved

---

plugin.js
spec/plugin.spec.js

Hashing the html instead of just the text to make sure we get the correct sha hash required

Hashing the html instead of just the text

---

README.md
plugin.js
spec/plugin.spec.js

This will allow the `enabled` property to accept a function - this will allow conditionally turning on and off the CSP plugin for different HTMLWebpackPlugin compilations in the same webpack config file.

Allowing enabled to accept a function as well as a boolean

---

plugin.js
spec/plugin.spec.js

Ensure that the script- and style-src found on the `policyObj` are indeed arrays before applying `Array.prototype.concat`. 
This is necessary because `"'self'".concat("'sha256-xx'")` evaluates to `'self''sha256-xx'`, which is an invalid policy. The same bug does not appear when using an array, because `buildPolicy` joins each item in the array with a space between, while it leaves strings intact.
I was unable to sign the CLA using the link provided, it just showed a blank page for me.

Allow string values for script- and style-src policies

---

.prettierrc

Add `.prettierrc` config file to allow editors to pick up the same settings as those defined in `.eslintrc.js`
I managed to autoformat the files incorrectly a few times when working on #9. Was a bit annoying, maybe this can help someone in the future :)
Not sure what tests to write to cover this. IMO it isn't necessary since we have eslint rules to enforce the rules :) 
Couldn't access the CLA agreement found on cla-assistant.io :/

Add .prettierrc config file

---

plugin.js

Implement Webpack 4 hooks API.

Webpack 4 refactor

---

plugin.js
spec/fixtures/with-no-meta-tag.html
spec/plugin.spec.js

Add <meta> tag if it doesn't exist. Feature request in #12

Add meta tag if it doesn't exist

---

plugin.js
spec/plugin.spec.js

Modern browsers ignore the `'unsafe-inline'` CSP setting [if any hash or nonce exists in that directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Sources). This means that this plugin's automatic `sha256` hashes that it generates for inline scripts and styles implicitly disable `'unsafe-inline'` for modern browsers even if the developer explicitly wants `'unsafe-inline'` enabled.
This PR addresses the issue by adding an option to the plugin config to disable the implicit hashing. Setting `hashIfUnsafeInlinePresent` to `false` when initializing the plugin will make it skip hashing if a `script-src` or `style-src` directive contains an `'unsafe-inline'` value.

Add option to skip hashing if unsafe-inline is present

---

README.md
plugin.js
spec/plugin.spec.js

Hi,
This should disable the plugin from htmlwebpackplugin. this comes handy in a very large applications where CSP plugin is not expected to add meta tags for particular/few html files

feat: disable the plugin from HTMLWebpackPlugin

---

README.md
plugin.js
spec/plugin.spec.js

Previously, we added functionality to not generate hashes if `unsafe-inline` was specifically added to a policy by a developer, however, this breaks csp backwards compatibility with older browsers.
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src):
> Specifying nonce makes a modern browser ignore 'unsafe-inline' which could still be set for older browsers without nonce support
The same applies to hashes
This PR has added in a new config option (`devAllowUnsafe`) to allow the developer to stop inline hash processing if set. Otherwise, a policy will be created with both `unsafe-inline` and inline script hashes

An option for disabling unsafe inline

---

package.json
plugin.js

Building off of PR https://github.com/slackhq/csp-html-webpack-plugin/pull/16/, this PR adds HtmlWebpackPlugin@4 support to the CspHtmlWebpackPlugin.
Opted to move the require to the top of the file to ensure we load it once and reference it - also keeps the requires a little more together for easier debugging.
Credits go to @sibiraj-s for the initial implementation in the PR linked above

Adding HtmlWebpackPlugin@4 support

---

package.json
plugin.jest.js
plugin.js
test-utils/webpack-helpers.js

Nonce attributes will now be added to external scripts and styles whos hostnames haven't been defined in the CSP policy already. If, however, you add your public path to your CSP policy, a nonce won't be added for that specific script tag.
Before merging this, we should check to see if [`strict-dynamic`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic) exists in the policy - if it does, we will still need to generate nonce ids for all external assets, even if their host has been allowed in the CSP policy

Adding nonce attrs to external scripts where their host hasnt been defined in the CSP already

---

README.md
package-lock.json
package.json

Fixes #32 
Replaces https://github.com/slackhq/csp-html-webpack-plugin/pull/33 with a signed commit
- Moved `babel-jest` to devDependencies
- Upgraded `jest` to fix audit report
- Upgraded all other packages to put them on their latest versions
- Removed an example option in the README which is no longer present

Dependency Upgrades, and Readme fix

---

plugin.js

Ensuring that html webpack plugin hooks are available before attempting to register callbacks on hooks - if html webpack plugin has not been defined, this will error out

Ensuring that html webpack plugin hooks are available

---

README.md
plugin.jest.js
plugin.js

This PR allows a developer to define a custom `processFn` method to overwrite the default behaviour of inlining the policy into the head of the document we're currently processing.
Covers a request from https://github.com/slackhq/csp-html-webpack-plugin/pull/44, and an issue raised in https://github.com/slackhq/csp-html-webpack-plugin/issues/57
- Moved the current processing into a `defaultProcessFn` function, and made it the default behaviour so as to be backwards compatible.
- Allowed the developer to overwrite this function with a custom function defined in either the `CspHtmlWebpackPlugin` `additionalOpts` object, or from the `HtmlWebpackPlugin` instance `cspPlugin` object. This can allow for different processing functions per `HtmlWebpackPlugin` instance
- Added tests
- Updated …

Adding ability to overwrite the default processFn method with a custom one.

---

.travis.yml
jest.config.js
package-lock.json
package.json
plugin.jest.js
plugin.js
test-utils/webpack-helpers.js

Upgrade NPM packages to their latest versions to remove the latest vulnerabilities reported
- Upgraded packages
- Ran `eslint --fix` to update code to match new default style rules

Upgrade NPM packages

---

package.json

Removing codecov token
Its not needed int a public repo when run from travis
- Removed the token and verified that codecov still generates reports as expected.
- Token has been rotated

Removing codecov token

---

package-lock.json
package.json
plugin.js

Upgrading dev and peer dependencies.
- `webpack` 5 is now used when testing this plugin
- `html-webpack-plugin` 5 is now used when testing this plugin
- Updating the peer dependency requirements to ensure only `webpack` 4 & 5, and only `html-webpack-plugin` 4 & 5 are supported.

Upgrade more dev deps and peer dep requirements

---

.eslintrc.js
package-lock.json
package.json
plugin.jest.js
plugin.js
test-utils/fixtures/with-escaped-html.html
test-utils/fixtures/with-noscript-tags.html
test-utils/fixtures/with-xhtml.html

This PR fixes a few outstanding issues:
- Escaped HTML becomes unescaped (https://github.com/slackhq/csp-html-webpack-plugin/issues/40). Upgrading cheerio to rc5 has fixed this issue.
- `xhtml` option in `html-webpack-plugin` was not honored (https://github.com/slackhq/csp-html-webpack-plugin/issues/61). We are now using `htmlparser2` which fixes this. Originally, I tried using the `htmlparser2` fix [listed on the cheerio readme](https://github.com/cheeriojs/cheerio#loading), but it failed to convert some of the fixture html files _back_ to a string. By using the hidden option `_useHtmlParser2` as suggested by @bigotilda, we're able to use `htmlparser2` to read the contents, and `parse5` to write the contents.
- Elements with `noscript` tags were not included in the policy …

HTML Parsing Fixes

---

README.md
package.json
plugin.jest.js
plugin.js

Enables to manipulate the webpack build to add an asset file to the build.
Discussed in https://github.com/slackhq/csp-html-webpack-plugin/issues/52

Add webpack compilation object to processfn
